name: Build and push latest image to ghcr

on:
  push:
    branches:
      - main-copy
  schedule:
    # Ideally, we would update the image every time the base image (p4lang/behavioral-model)
    # is updated, this is good enough.
    - cron: '15 0-23/4 * * *' # "At minute 15 past every 4th hour from midnight through 23."

jobs:
  build:
    if: ${{ github.repository == 'stolsma/ipdk' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: p4lang/p4c
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image to registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/ipdk-p4c:latest 
        cache-from: type=gha
        cache-to: type=gha,mode=max